name: Discord Star Notification

on:
  watch:
    types: [started]

jobs:
  star-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [{
              "title": "⭐ New Repository Star!",
              "description": "[**${{ github.actor }}**](https://github.com{{ github.actor }}) just starred the repository!",
              "color": 16772096,
              "url": "https://github.com{{ github.repository }}"
            }]
          }' \
          $WEBHOOK_URL
